### ISSUE TITLE
Format of Currency

### ISSUE THREAD

**Issue by Overjoy06-Creator** [Seniru/TFM_Clicker#10]
While testing the module out we figured currency is displayed as in scientific notation such as 2.3453545E7 We will try something to fix this issue

**Comment by Seniru** [comment]
We are actively finding a way to solve this. This issue is open for suggestions to solve this issue

**Comment by Seniru** [comment]
A new bug discovered related to this!
When a player creates a job with absolutely large salary  (about trillions) lua will turn them into an unpredictable number. 
For example I entered 99999999999999999999999999999 as the salary and lua parsed it as -693................................ (something like that)
Because of this case we'll have to set a limit for the salary of a job.

Apart from this solution I m working on another solution which can convert numbers into a string which will append an affix such as "K", "M", "B" or "T" at the end of the number

For example 10000 will give 10K.

These are the only ways that we can fix this issue programmatically

**Comment by Seniru** [comment]
Added "help wanted" and "very important"  labels because of the criticality of this bug

**Comment by Seniru** [comment]
Fixed the issue with the commit https://github.com/Seniru/TFM_Clicker/commit/f79e200c363b5b63cf1f2068f2d6abece90b3d43. Opened for further testing of the feature
@Overjoy06-Creator
